/**
 * dummy.ts
 *
 * Demo network definition for the East Java paddy irrigation twin.
 * This is the shape that a real GeoJSON parser should produce.
 *
 * mapData is generated by a small helper rather than hardcoded because
 * a 22×15 = 330-cell literal would be impractical to maintain.
 * The helper is intentionally local — no exports, no external deps.
 *
 * ── Coordinate system ────────────────────────────────────────────────────
 * [col, row] grid indices, origin top-left.
 * Row 0 = high elevation (reservoir/intake end).
 * Row 14 = low elevation (farm plot end).
 *
 * ── Cell type priority (used in generateMapData) ─────────────────────────
 * source > canal > plot > terrain
 *
 * ── Layout (22 cols × 15 rows) ────────────────────────────────────────────
 *   Row 0       Reservoir (source)
 *   Rows 1-7    Main canal descends south, branches left and right
 *   Rows 8-10   West/East branches curve out to the plot areas
 *   Rows 10-13  Five farm plot polygons in the lower basin
 *
 * ── Elevation model ───────────────────────────────────────────────────────
 * Base elevation per cell = slope + lateral
 *   slope   = 12 − (row / 14) × 10          (12 m at top → 2 m at bottom)
 *   lateral = sin(col / 21 × π) × 1.2       (bowl shape, peaks at center)
 *
 * buildGrid in physics.logic.ts then applies:
 *   canal cells  → base − CANAL_DEPTH (2 m)   preferred flow trench
 *   plot  cells  → base − PLOT_DEPTH  (2.5 m) paddy-field basin
 * This ensures gravity flow runs: source → canal → plot.
 */

import type { I_map, I_network_data } from "./models";

// ── RAW NETWORK DEFINITIONS ───────────────────────────────────────────────
// Defined as local constants first so generateMapData can reference them
// when deciding which cells are canals, sources, or plots.

const DEMO_SOURCES: [number, number][] = [
    [11, 0],
];

const DEMO_CANALS: I_network_data["canals"] = [
    {
        id: "main",
        label: "Main Canal",
        waypoints: [
            [11, 0], [11, 1], [11, 2], [11, 3],
            [11, 4], [11, 5], [11, 6], [11, 7],
        ],
    },
    {
        id: "west",
        label: "West Branch",
        waypoints: [
            [11, 7], [9, 7], [7, 7], [5, 7],
            [4, 8],  [4, 9], [4, 10],
        ],
    },
    {
        id: "east",
        label: "East Branch",
        waypoints: [
            [11, 7],  [13, 7], [15, 7], [17, 7],
            [18, 8],  [18, 9], [18, 10],
        ],
    },
];

const DEMO_PLOTS: I_network_data["plots"] = [
    { id: "p_w1", label: "Plot W-1", polygon: [[0,  10], [4,  10], [4,  14], [0,  14]] },
    { id: "p_w2", label: "Plot W-2", polygon: [[4,  10], [9,  10], [9,  14], [4,  14]] },
    { id: "p_c1", label: "Plot C-1", polygon: [[9,  11], [13, 11], [13, 14], [9,  14]] },
    { id: "p_e1", label: "Plot E-1", polygon: [[13, 10], [18, 10], [18, 14], [13, 14]] },
    { id: "p_e2", label: "Plot E-2", polygon: [[18, 10], [21, 10], [21, 14], [18, 14]] },
];

const DEMO_GATES: I_network_data["gates"] = [
    { id: "g_main", label: "Main Gate",        cell: [11, 3], isOpen: true  },
    { id: "g_west", label: "West Branch Gate", cell: [7,  7], isOpen: true  },
    { id: "g_east", label: "East Branch Gate", cell: [15, 7], isOpen: false },
];

// ── MAP DATA GENERATOR ────────────────────────────────────────────────────

/**
 * generateMapData — builds the I_map[][] grid from the raw network definitions.
 *
 * Cell type priority:  source > canal > plot > terrain
 * This prevents canal endpoint cells from being overwritten by plot type
 * (e.g. [4,10] is a canal endpoint AND within plot W-2's bounding box —
 * canal wins, so water can flow from canal → adjacent plot cells).
 *
 * Elevation uses the same slope + lateral formula that the old
 * buildElevationMap used, keeping the terrain visual identical.
 * buildGrid in physics.logic.ts applies the per-type depth offsets.
 */
function generateMapData(cols: number, rows: number): I_map[][] {
    // Build priority lookup sets from the definitions above
    const sourceSet = new Set<string>(
        DEMO_SOURCES.map(([c, r]) => `${c}_${r}`)
    );

    const canalSet = new Set<string>(
        DEMO_CANALS.flatMap(canal => canal.waypoints).map(([c, r]) => `${c}_${r}`)
    );
    // Source cells take priority — remove them from canalSet so the type
    // assignment below correctly assigns them as 'source'
    for (const id of sourceSet) canalSet.delete(id);

    const plotSet = new Set<string>();
    for (const plot of DEMO_PLOTS) {
        const cs   = plot.polygon.map(([c]) => c);
        const rs   = plot.polygon.map(([, r]) => r);
        const cMin = Math.min(...cs);
        const cMax = Math.max(...cs);
        const rMin = Math.min(...rs);
        const rMax = Math.max(...rs);

        for (let r = rMin; r < rMax; r++) {
            for (let c = cMin; c < cMax; c++) {
                const id = `${c}_${r}`;
                // Canal and source cells take priority over plot
                if (!sourceSet.has(id) && !canalSet.has(id)) {
                    plotSet.add(id);
                }
            }
        }
    }

    // Build the 2D map array
    const map: I_map[][] = [];

    for (let row = 0; row < rows; row++) {
        const mapRow: I_map[] = [];

        for (let col = 0; col < cols; col++) {
            // Base elevation: primary slope + lateral bowl
            const slope    = 12 - (row / (rows - 1)) * 10;
            const lateral  = Math.sin((col / (cols - 1)) * Math.PI) * 1.2;
            const elevation = +(slope + lateral).toFixed(2);

            const key = `${col}_${row}`;
            let type: string;

            if      (sourceSet.has(key)) type = "source";
            else if (canalSet.has(key))  type = "canal";
            else if (plotSet.has(key))   type = "plot";
            else                          type = "terrain";

            mapRow.push({ elevation, type });
        }

        map.push(mapRow);
    }

    return map;
}

// ── EXPORT ────────────────────────────────────────────────────────────────

export const DEMO_DATA: I_network_data = {
    /**
     * mapData drives grid construction in buildInitialGrid.
     * Generated from the definitions above so the visual layout
     * matches the canal waypoints and plot polygons exactly.
     */
    mapData: generateMapData(22, 15),

    /** Source cells — must match cells marked type:'source' in mapData. */
    sources: DEMO_SOURCES,

    /**
     * Canal waypoints — used by the renderer for smooth bezier river lines.
     * Not used for grid construction (that comes from mapData).
     */
    canals: DEMO_CANALS,

    /**
     * Plot polygons — used by the renderer and plotWaterLevel.
     * Not used for grid construction (that comes from mapData).
     */
    plots: DEMO_PLOTS,

    /**
     * Gates — used by both the simulation (flow blocking) and renderer.
     * cell [col, row] must match a canal cell in mapData.
     */
    gates: DEMO_GATES,
};